allowBuilds:
  '@parcel/watcher': true
  core-js: false
  es5-ext: false
  esbuild: true
  vue-demi: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - es5-ext
  - esbuild
  - vue-demi
